sonar.projectKey=StudentManagementSystem
sonar.projectName=Student Management System
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Force SonarScanner to calculate duplication on Java & plain files
sonar.cpd.exclusions=
sonar.cpd.java.minimumLines=5
sonar.cpd.java.minimumTokens=20
